# Gunakan image resmi Python
FROM python:3.10-slim

# Tentukan direktori kerja di dalam container
WORKDIR /app

# Salin file requirements.txt dan install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua file proyek ke dalam container
COPY . /app/

# Meng-expose port (hanya untuk dokumentasi, Cloud Run akan mengabaikan ini)
EXPOSE 8080

# Tentukan perintah untuk menjalankan aplikasi
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
